# Verwenden Sie das Nginx-Bild aus dem Docker Hub
FROM nginx:latest

# Kopieren Sie die HTML-Datei in den Container
COPY ./index.html /usr/share/nginx/html/index.html

# Kopieren Sie die CSS-Datei in den Container
COPY ./style.css /usr/share/nginx/html/style.css

# Kopieren Sie die JS-Datei in den Container
COPY ./script.js /usr/share/nginx/html/script.js