# Verwenden des nginx
FROM nginx:latest

# Dateien in den Container kopieren 
COPY ./index.html /usr/share/nginx/html/index.html

COPY ./style.css /usr/share/nginx/html/style.css

COPY ./script.js /usr/share/nginx/html/script.js



